### ISSUE TITLE
执行rails s错误

### ISSUE THREAD

**Issue by chunlea** [xdite/bootcolor#1]
我这边创建了一个新的rails程序，然后挂上bootcolor，提示错误。

```
/Users/chunlea/Code/tmp/bootcolor/config/application.rb:10:in `<module:Bootcolor>': uninitialized constant Bootcolor::Rails::Application (NameError)
    from /Users/chunlea/Code/tmp/bootcolor/config/application.rb:9:in `<top (required)>'
    from /Users/chunlea/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/commands.rb:78:in `require'
    from /Users/chunlea/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/commands.rb:78:in `block in <top (required)>'
    from /Users/chunlea/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/commands.rb:75:in `tap'
    from /Users/chunlea/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/commands.rb:75:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

难道是版本兼容问题？

**Comment by xdite** [comment]
won't work in Rails 4. I will find a way to fix
